//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanValidation.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanValidation.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The date is in the future..
        /// </summary>
        internal static string AgainstDateInFuture {
            get {
                return ResourceManager.GetString("AgainstDateInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The date is in the past..
        /// </summary>
        internal static string AgainstDateInPast {
            get {
                return ResourceManager.GetString("AgainstDateInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The date/time is in the future..
        /// </summary>
        internal static string AgainstDateTimeInFuture {
            get {
                return ResourceManager.GetString("AgainstDateTimeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The date/time is in the past..
        /// </summary>
        internal static string AgainstDateTimeInPast {
            get {
                return ResourceManager.GetString("AgainstDateTimeInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value is default..
        /// </summary>
        internal static string AgainstDefault {
            get {
                return ResourceManager.GetString("AgainstDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value is empty..
        /// </summary>
        internal static string AgainstEmpty {
            get {
                return ResourceManager.GetString("AgainstEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The values are equal..
        /// </summary>
        internal static string AgainstEqual {
            get {
                return ResourceManager.GetString("AgainstEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The condition is false..
        /// </summary>
        internal static string AgainstFalse {
            get {
                return ResourceManager.GetString("AgainstFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value is contained in the list..
        /// </summary>
        internal static string AgainstIn {
            get {
                return ResourceManager.GetString("AgainstIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The values are different..
        /// </summary>
        internal static string AgainstNotEqual {
            get {
                return ResourceManager.GetString("AgainstNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value is not contained in the list..
        /// </summary>
        internal static string AgainstNotIn {
            get {
                return ResourceManager.GetString("AgainstNotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value is null..
        /// </summary>
        internal static string AgainstNull {
            get {
                return ResourceManager.GetString("AgainstNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value is out of the range..
        /// </summary>
        internal static string AgainstOutOfRange {
            get {
                return ResourceManager.GetString("AgainstOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value is in the range..
        /// </summary>
        internal static string AgainstRange {
            get {
                return ResourceManager.GetString("AgainstRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The time is in the future..
        /// </summary>
        internal static string AgainstTimeInFuture {
            get {
                return ResourceManager.GetString("AgainstTimeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The time is in the past..
        /// </summary>
        internal static string AgainstTimeInPast {
            get {
                return ResourceManager.GetString("AgainstTimeInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The condition is true..
        /// </summary>
        internal static string AgainstTrue {
            get {
                return ResourceManager.GetString("AgainstTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value is null or white space..
        /// </summary>
        internal static string AgainstWhiteSpace {
            get {
                return ResourceManager.GetString("AgainstWhiteSpace", resourceCulture);
            }
        }
    }
}
